import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import ContainerCalendar from "../components/containerCalendar";
import Weather from "../components/weather";
import { getWeather } from "../services/weather-service";
import { fetchWeather, filterWeather } from "../store/slices/weatherSlice";
import { wrapper } from "../store/store";

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
  const { query } = context;
  const { data } = await getWeather(query.lat, query.lon);

  if (!data) {
    return { notFound: true };
  }
  store.dispatch(fetchWeather(data));
});

const Countrys = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(filterWeather(new Date().toString()));
  }, []);

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-between items-start m-5">
        <Weather />
        <ContainerCalendar />
      </main>
    </div>
  );
};

export default Countrys;
