import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center flex-col">
        <p className="text-3xl font-bold mt-10 cursor-pointer">5 Days Weather Forecast</p>
        <p className="text-3xl font-bold m-10 cursor-pointer">Please Choose Country</p>
      </main>
    </div>
  );
};

export default Home;
